export const copy = {
  de: {
    appName: 'Wolkenpost',
    documentTitle: 'Wolkenpost – Deine Zeichnung reist mit dem Wind',
    metaDescription: 'Zeichne ein Flugobjekt und schicke es mit echten Winddaten auf eine stilisierte Weltreise.',
    shell: {
      skip: 'Zum Inhalt',
      homeLabel: 'MilosApps Startseite',
      appNav: 'App-Navigation',
      language: 'Sprache',
      allApps: 'Alle Apps',
      ready: 'bereit',
      offline: 'offline',
    },
    hero: {
      eyebrow: 'Wolkenpost',
      heading: 'Zeichne. Lass es fliegen.',
      lead: 'Starte grob. Die private Modellroute folgt echten Winddaten.',
      start: 'Jetzt loszeichnen',
    },
    objectTypes: {
      cloud: { label: 'Wolke', hint: 'hoch und weit, 18 Stunden' },
      balloon: { label: 'Ballon', hint: 'ruhig schwebend, 12 Stunden' },
      seed: { label: 'Samen', hint: 'nah am Boden, 3 Stunden' },
      'paper-plane': { label: 'Papierflieger', hint: 'kurzer Flug, 90 Minuten' },
    },
    drawing: {
      kicker: 'Dein Reisender',
      heading: 'Was fliegt heute?',
      groupLabel: 'Flugobjekt',
      addOutline: 'Umriss ergänzen',
      undo: 'Rückgängig',
      clear: 'Leeren',
      canvasLabel: 'Zeichenfläche. Mit Maus, Touch oder Stift zeichnen. Tastatur: Leertaste startet und beendet einen Strich, Pfeiltasten bewegen den Zeichenstift.',
      keyboardMode: 'Tastaturstrich aktiv · Pfeiltasten bewegen · Leertaste beendet · Escape verwirft',
      pointerMode: 'Strich wird gezeichnet',
      readyMode: 'Bereit zum Zeichnen',
      help: 'Striche bleiben nur auf diesem Gerät. Mit Steuerung Z oder der Rückgängig-Taste wird der letzte Strich entfernt.',
    },
    map: {
      kicker: 'Der Startpunkt',
      heading: 'Wo geht die Reise los?',
      selected: 'Gewählter Start',
      search: 'Ort oder Region',
      placeholder: 'z. B. Köln, Bayern oder London',
      locating: 'Ortung läuft …',
      locate: 'Meinen Ort verwenden',
      suggestions: 'Ortsvorschläge',
      noResults: 'Kein Treffer – tippe stattdessen auf die Karte.',
      fineTune: 'Startpunkt mit Tastatur fein einstellen',
      latitude: 'Breitengrad',
      longitude: 'Längengrad',
      canvasLabel: 'Interaktive stilisierte Weltkarte. Klicken oder mit den Pfeiltasten einen groben Startpunkt wählen. Die Ortssuche darunter ist die zugänglichere Alternative.',
      point: 'Punkt auf der Karte',
      lastStart: 'Letzter Start',
      storedLocally: 'lokal gespeichert',
    },
    launch: {
      kicker: 'Bereit?',
      heading: 'Lass den Wind entscheiden.',
      description: 'Wolkenpost lädt neun grobe Windpunkte rund um deinen Start und berechnet die Route auf diesem Gerät. Das ist eine spielerische Modellroute, keine Navigation.',
      loading: 'Live-Wind wird gelesen …',
      cancel: 'Abbrechen',
      start: 'Flug mit Live-Wind starten',
      missingDrawing: 'Zeichne zuerst einen Strich oder ergänze einen Umriss.',
    },
    windErrors: {
      offline: 'Du bist gerade offline. Deine Zeichnung bleibt da – Live-Wind braucht eine Verbindung.',
      timeout: 'Der Winddienst hat zu lange gebraucht. Du kannst erneut versuchen oder bewusst den Demo-Wind wählen.',
      network: 'Live-Wind ist gerade nicht erreichbar. Nichts wurde verloren.',
      invalid: 'Die Winddaten waren unvollständig. Bitte versuche es noch einmal.',
    },
    errorPanel: {
      kicker: 'Live-Wind fehlt',
      demoExplanation: 'Demo-Wind ist ein festes, synthetisches Testfeld vom 30. Juli 2026. Es wird niemals als echte Messung dargestellt.',
      retry: 'Live-Wind erneut versuchen',
      demo: 'Bewusst mit Demo-Wind starten',
    },
    result: {
      liveRoute: 'Live-Windroute',
      demoRoute: 'Demo-Windroute',
      near: (place: string) => `nahe ${place}`,
      arrived: (endLabel: string) => `Angekommen ${endLabel}.`,
      from: (startLabel: string) => `Von ${startLabel}, ohne genaue Koordinaten in der Ergebnisgrafik.`,
      liveData: 'echte Modelldaten',
      demoData: 'synthetischer Demo-Wind',
      distance: 'Strecke',
      duration: 'Flugzeit',
      average: 'Ø Windreise',
      maximum: 'Spitze',
      dataTime: 'Datenstand',
      source: 'Quelle / Modell',
      exporting: 'Grafik wird erstellt …',
      save: 'Ergebnisbild speichern',
      share: 'Teilen',
      again: 'Noch eine Reise',
    },
    settings: {
      summary: 'Darstellung, Bewegung und lokale Daten',
      kicker: 'Auf diesem Gerät',
      heading: 'Deine Einstellungen',
      description: 'Zeichnung, Einstellungen und grober Start bleiben nur in diesem Browser.',
      theme: 'Darstellung',
      themeSystem: 'Wie das Gerät',
      themeLight: 'Hell',
      themeDark: 'Dunkel',
      motion: 'Bewegung',
      motionSystem: 'Wie das Gerät',
      motionFull: 'Route animieren',
      motionReduced: 'Route sofort zeigen',
      sound: 'Leiser Startton',
      soundHint: 'Aus, bis du ihn bewusst einschaltest',
      delete: 'Lokale Daten löschen',
      deleteGroup: 'Lokale Daten wirklich löschen',
      deleteQuestion: 'Zeichnung und Einstellungen wirklich löschen?',
      deleteConfirm: 'Ja, löschen',
      cancel: 'Abbrechen',
      storageWarning: 'Dieser Browser konnte lokale Änderungen nicht speichern. Die aktuelle Sitzung funktioniert weiter.',
    },
    footer: {
      description: 'Deine Zeichnung reist mit dem Wind – privat, verspielt und ohne Anmeldung.',
      credits: 'Datenquellen und Nutzungshinweise',
      legalNav: 'Rechtliches',
      legal: 'Impressum',
      privacy: 'Datenschutz',
      home: 'MilosApps',
      wind: 'Winddaten: Open‑Meteo · CC BY 4.0',
      ownWork: 'Weltbild und Gestaltung: eigenes Werk',
      disclaimer: 'Keine Navigation oder Wetterwarnung',
    },
    export: {
      title: 'Meine Wolkenpost',
      hours: 'Stunden',
      liveSource: (label: string, model: string) => `Modellroute mit ${label}, ${model}`,
      demoSource: 'Modellroute mit klar gekennzeichnetem synthetischem Demo-Wind',
      disclaimer: 'wolkenpost · keine Navigation · Start nur grob dargestellt',
    },
    announcements: {
      ready: 'Wolkenpost ist bereit.',
      connectionRestored: 'Verbindung wieder da. Live-Wind kann erneut geladen werden.',
      offline: 'Offline. Deine Zeichnung bleibt auf diesem Gerät.',
      objectSelected: (label: string) => `${label} ausgewählt.`,
      startSelected: (place: string) => `Startpunkt ${place} gewählt.`,
      geolocationUnsupported: 'Ortung wird von diesem Browser nicht unterstützt. Die Ortsuche bleibt verfügbar.',
      geolocationPrompt: 'Der Browser fragt nach deiner Erlaubnis für den Standort.',
      geolocationDenied: 'Ortung wurde nicht erlaubt. Das ist völlig okay – suche einen Ort oder tippe auf die Karte.',
      geolocationTimeout: 'Die Ortung hat zu lange gebraucht. Suche stattdessen einen Ort oder versuche es erneut.',
      geolocationUnavailable: 'Der Standort war nicht verfügbar. Ortssuche und Karte funktionieren weiterhin.',
      routeReady: (distance: number, endLabel: string) => `Die Route ist fertig: ${distance} Kilometer bis ${endLabel}.`,
      liveLoading: 'Live-Wind wird geladen. Deine Zeichnung bleibt bedienbar.',
      windCancelled: 'Windabruf abgebrochen. Deine Zeichnung und dein Startpunkt sind erhalten.',
      imageSaved: 'Ergebnisgrafik gespeichert. Sie enthält keine exakten Startkoordinaten.',
      imageFailed: 'Die Ergebnisgrafik konnte in diesem Browser nicht gespeichert werden.',
      shared: 'Wolkenpost wurde an die ausgewählte App übergeben.',
      shareCopied: 'Der Link zur Wolkenpost wurde kopiert. Zeichnung und Startpunkt bleiben privat.',
      shareFailed: 'Teilen war nicht möglich. Du kannst das Bild stattdessen speichern.',
      dataDeleted: 'Lokale Wolkenpost-Daten wurden von diesem Gerät gelöscht.',
      strokesSaved: (count: number) => `${count} Strich${count === 1 ? '' : 'e'} gespeichert.`,
      strokeUndone: 'Letzten Strich zurückgenommen.',
      outlineAdded: (label: string) => `${label}-Umriss ergänzt.`,
      canvasCleared: 'Zeichenfläche geleert.',
    },
    share: {
      title: 'Meine Wolkenpost',
      text: (distance: number, endLabel: string) => `Meine Wolkenpost reiste ${distance} km ${endLabel}.`,
    },
  },
  en: {
    appName: 'Cloud Post',
    documentTitle: 'Cloud Post – Your drawing travels with the wind',
    metaDescription: 'Draw a flying object and send it around a stylised world using real wind data.',
    shell: {
      skip: 'Skip to content',
      homeLabel: 'MilosApps home',
      appNav: 'App navigation',
      language: 'Language',
      allApps: 'All apps',
      ready: 'ready',
      offline: 'offline',
    },
    hero: {
      eyebrow: 'Cloud Post',
      heading: 'Draw it. Let it fly.',
      lead: 'Start roughly. The private model route follows real wind data.',
      start: 'Start drawing',
    },
    objectTypes: {
      cloud: { label: 'Cloud', hint: 'high and far, 18 hours' },
      balloon: { label: 'Balloon', hint: 'floating gently, 12 hours' },
      seed: { label: 'Seed', hint: 'near the ground, 3 hours' },
      'paper-plane': { label: 'Paper plane', hint: 'short flight, 90 minutes' },
    },
    drawing: {
      kicker: 'Your traveller',
      heading: 'What will fly today?',
      groupLabel: 'Flying object',
      addOutline: 'Add outline',
      undo: 'Undo',
      clear: 'Clear',
      canvasLabel: 'Drawing canvas. Draw with a mouse, touch or pen. Keyboard: Space starts and ends a stroke; arrow keys move the drawing cursor.',
      keyboardMode: 'Keyboard stroke active · Arrow keys move · Space finishes · Escape discards',
      pointerMode: 'Drawing a stroke',
      readyMode: 'Ready to draw',
      help: 'Strokes stay on this device. Press Control Z or use the Undo button to remove the last stroke.',
    },
    map: {
      kicker: 'The starting point',
      heading: 'Where does the journey begin?',
      selected: 'Selected start',
      search: 'Place or region',
      placeholder: 'e.g. Cologne, Bavaria or London',
      locating: 'Locating …',
      locate: 'Use my location',
      suggestions: 'Place suggestions',
      noResults: 'No match – tap the map instead.',
      fineTune: 'Fine-tune the starting point with the keyboard',
      latitude: 'Latitude',
      longitude: 'Longitude',
      canvasLabel: 'Interactive stylised world map. Click or use the arrow keys to choose an approximate starting point. The place search below is the more accessible alternative.',
      point: 'Point on the map',
      lastStart: 'Last start',
      storedLocally: 'stored locally',
    },
    launch: {
      kicker: 'Ready?',
      heading: 'Let the wind decide.',
      description: 'Cloud Post loads nine coarse wind points around your start and calculates the route on this device. It is a playful model route, not navigation.',
      loading: 'Reading live wind …',
      cancel: 'Cancel',
      start: 'Start flight with live wind',
      missingDrawing: 'Draw a stroke first or add an outline.',
    },
    windErrors: {
      offline: 'You are offline. Your drawing is safe – live wind needs a connection.',
      timeout: 'The wind service took too long. You can retry or deliberately choose demo wind.',
      network: 'Live wind is currently unavailable. Nothing was lost.',
      invalid: 'The wind data was incomplete. Please try again.',
    },
    errorPanel: {
      kicker: 'Live wind missing',
      demoExplanation: 'Demo wind is a fixed synthetic test field from 30 July 2026. It is never presented as a real measurement.',
      retry: 'Try live wind again',
      demo: 'Deliberately use demo wind',
    },
    result: {
      liveRoute: 'Live-wind route',
      demoRoute: 'Demo-wind route',
      near: (place: string) => `near ${place}`,
      arrived: (endLabel: string) => `Arrived ${endLabel}.`,
      from: (startLabel: string) => `From ${startLabel}, without exact coordinates in the result image.`,
      liveData: 'real model data',
      demoData: 'synthetic demo wind',
      distance: 'Distance',
      duration: 'Flight time',
      average: 'Ø wind journey',
      maximum: 'Peak',
      dataTime: 'Data time',
      source: 'Source / model',
      exporting: 'Creating image …',
      save: 'Save result image',
      share: 'Share',
      again: 'Another journey',
    },
    settings: {
      summary: 'Appearance, motion and local data',
      kicker: 'On this device',
      heading: 'Your settings',
      description: 'Your drawing, settings and approximate start stay only in this browser.',
      theme: 'Appearance',
      themeSystem: 'Follow device',
      themeLight: 'Light',
      themeDark: 'Dark',
      motion: 'Motion',
      motionSystem: 'Follow device',
      motionFull: 'Animate route',
      motionReduced: 'Show route immediately',
      sound: 'Quiet launch tone',
      soundHint: 'Off until you consciously enable it',
      delete: 'Delete local data',
      deleteGroup: 'Really delete local data',
      deleteQuestion: 'Really delete the drawing and settings?',
      deleteConfirm: 'Yes, delete',
      cancel: 'Cancel',
      storageWarning: 'This browser could not save local changes. The current session will keep working.',
    },
    footer: {
      description: 'Your drawing travels with the wind – private, playful and without an account.',
      credits: 'Data sources and usage notes',
      legalNav: 'Legal',
      legal: 'Legal notice',
      privacy: 'Privacy',
      home: 'MilosApps',
      wind: 'Wind data: Open‑Meteo · CC BY 4.0',
      ownWork: 'World artwork and design: original work',
      disclaimer: 'Not navigation or a weather warning',
    },
    export: {
      title: 'My Cloud Post',
      hours: 'hours',
      liveSource: (label: string, model: string) => `Model route using ${label}, ${model}`,
      demoSource: 'Model route using clearly labelled synthetic demo wind',
      disclaimer: 'cloud post · not navigation · start shown approximately',
    },
    announcements: {
      ready: 'Cloud Post is ready.',
      connectionRestored: 'Connection restored. Live wind can be loaded again.',
      offline: 'Offline. Your drawing stays on this device.',
      objectSelected: (label: string) => `${label} selected.`,
      startSelected: (place: string) => `Starting point ${place} selected.`,
      geolocationUnsupported: 'Location is not supported by this browser. Place search remains available.',
      geolocationPrompt: 'The browser is asking for permission to use your location.',
      geolocationDenied: 'Location permission was declined. That is completely fine – search for a place or tap the map.',
      geolocationTimeout: 'Location took too long. Search for a place instead or try again.',
      geolocationUnavailable: 'Location was unavailable. Place search and the map still work.',
      routeReady: (distance: number, endLabel: string) => `The route is ready: ${distance} kilometres to ${endLabel}.`,
      liveLoading: 'Loading live wind. Your drawing remains usable.',
      windCancelled: 'Wind request cancelled. Your drawing and starting point are preserved.',
      imageSaved: 'Result image saved. It contains no exact starting coordinates.',
      imageFailed: 'The result image could not be saved in this browser.',
      shared: 'Cloud Post was handed to the selected app.',
      shareCopied: 'The Cloud Post link was copied. Your drawing and starting point stay private.',
      shareFailed: 'Sharing was not possible. You can save the image instead.',
      dataDeleted: 'Local Cloud Post data was deleted from this device.',
      strokesSaved: (count: number) => `${count} stroke${count === 1 ? '' : 's'} saved.`,
      strokeUndone: 'Last stroke undone.',
      outlineAdded: (label: string) => `${label} outline added.`,
      canvasCleared: 'Drawing canvas cleared.',
    },
    share: {
      title: 'My Cloud Post',
      text: (distance: number, endLabel: string) => `My Cloud Post travelled ${distance} km ${endLabel}.`,
    },
  },
} as const;

export type SupportedLanguage = keyof typeof copy;
